[2022-09-11 16:51:39,663] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: FHVIngestionDag.wget scheduled__2019-11-01T06:00:00+00:00 [queued]>
[2022-09-11 16:51:39,674] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: FHVIngestionDag.wget scheduled__2019-11-01T06:00:00+00:00 [queued]>
[2022-09-11 16:51:39,675] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-09-11 16:51:39,675] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-09-11 16:51:39,675] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-09-11 16:51:39,871] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): wget> on 2019-11-01 06:00:00+00:00
[2022-09-11 16:51:39,889] {standard_task_runner.py:52} INFO - Started process 8280 to run task
[2022-09-11 16:51:39,909] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'FHVIngestionDag', 'wget', 'scheduled__2019-11-01T06:00:00+00:00', '--job-id', '98', '--raw', '--subdir', 'DAGS_FOLDER/FHV_ingest_19.py', '--cfg-path', '/tmp/tmpej_e9zv1', '--error-file', '/tmp/tmpvqle_ey5']
[2022-09-11 16:51:39,912] {standard_task_runner.py:77} INFO - Job 98: Subtask wget
[2022-09-11 16:51:40,163] {logging_mixin.py:109} INFO - Running <TaskInstance: FHVIngestionDag.wget scheduled__2019-11-01T06:00:00+00:00 [running]> on host 6ae512137983
[2022-09-11 16:51:40,446] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-09-11 16:51:40,613] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=FHVIngestionDag
AIRFLOW_CTX_TASK_ID=wget
AIRFLOW_CTX_EXECUTION_DATE=2019-11-01T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-11-01T06:00:00+00:00
[2022-09-11 16:51:40,615] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-09-11 16:51:40,616] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSL https://d37ci6vzurychx.cloudfront.net/trip-data/fhv_tripdata_2019-11.parquet > /opt/***/FHV_OUT_2019-11.parquet']
[2022-09-11 16:51:40,968] {subprocess.py:85} INFO - Output:
[2022-09-11 16:51:51,582] {subprocess.py:89} INFO - curl: (6) Could not resolve host: d37ci6vzurychx.cloudfront.net
[2022-09-11 16:51:51,588] {subprocess.py:93} INFO - Command exited with return code 6
[2022-09-11 16:51:51,623] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 6.
[2022-09-11 16:51:51,851] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=FHVIngestionDag, task_id=wget, execution_date=20191101T060000, start_date=20220911T165139, end_date=20220911T165151
[2022-09-11 16:51:52,338] {standard_task_runner.py:92} ERROR - Failed to execute job 98 for task wget
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 6.
[2022-09-11 16:51:52,540] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-09-11 16:51:52,681] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-09-15 05:24:15,310] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: FHVIngestionDag.wget scheduled__2019-11-01T06:00:00+00:00 [queued]>
[2022-09-15 05:24:15,336] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: FHVIngestionDag.wget scheduled__2019-11-01T06:00:00+00:00 [queued]>
[2022-09-15 05:24:15,337] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-09-15 05:24:15,337] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-09-15 05:24:15,337] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-09-15 05:24:15,383] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): wget> on 2019-11-01 06:00:00+00:00
[2022-09-15 05:24:15,387] {standard_task_runner.py:52} INFO - Started process 858 to run task
[2022-09-15 05:24:15,392] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'FHVIngestionDag', 'wget', 'scheduled__2019-11-01T06:00:00+00:00', '--job-id', '166', '--raw', '--subdir', 'DAGS_FOLDER/FHV_ingest_19.py', '--cfg-path', '/tmp/tmpibtd_ztx', '--error-file', '/tmp/tmp2j9b2txy']
[2022-09-15 05:24:15,393] {standard_task_runner.py:77} INFO - Job 166: Subtask wget
[2022-09-15 05:24:15,475] {logging_mixin.py:109} INFO - Running <TaskInstance: FHVIngestionDag.wget scheduled__2019-11-01T06:00:00+00:00 [running]> on host c071d865a623
[2022-09-15 05:24:15,552] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-09-15 05:24:15,601] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=FHVIngestionDag
AIRFLOW_CTX_TASK_ID=wget
AIRFLOW_CTX_EXECUTION_DATE=2019-11-01T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-11-01T06:00:00+00:00
[2022-09-15 05:24:15,602] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-09-15 05:24:15,603] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSL https://d37ci6vzurychx.cloudfront.net/trip-data/fhv_tripdata_2019-11.parquet > /opt/***/FHV_OUT_2019-11.parquet']
[2022-09-15 05:24:15,626] {subprocess.py:85} INFO - Output:
[2022-09-15 05:24:24,417] {subprocess.py:93} INFO - Command exited with return code 0
[2022-09-15 05:24:24,541] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=FHVIngestionDag, task_id=wget, execution_date=20191101T060000, start_date=20220915T052415, end_date=20220915T052424
[2022-09-15 05:24:24,623] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-09-15 05:24:24,694] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
